In [5]:
#week2day3
#Block A
#t1
import numpy as np

arr = np.arange(1, 21)

print("Array:", arr)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)
print("Size:", arr.size)
print("Mean:", arr.mean())

#t2
import numpy as np
arr = np.eye(5)
print(arr)
print("Sum:", arr.sum())

#t3
import numpy as np
arr = np.zeros((3,4))
arr[:,1] = 1
print(arr)

#t4
import numpy as np
x = np.linspace(0, 2*np.pi, 9)
y = np.sin(x)
print("Points:")
print(x)
print("Sine values:")
print(y)

#t5
import numpy as np
np.random.seed(42)
arr = np.random.randint(0,100,(4,4))
print(arr)
print("Shape:", arr.shape)
print("Minimum:", arr.min())
print("Maximum:", arr.max())
print("Mean:", arr.mean())

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Shape: (20,)
Data type: int64
Size: 20
Mean: 10.5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Sum: 5.0
[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]
Points:
[0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531]
Sine values:
[ 0.00000000e+00  7.07106781e-01  1.00000000e+00  7.07106781e-01
  1.22464680e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
 -2.44929360e-16]
[[51 92 14 71]
 [60 20 82 86]
 [74 74 87 99]
 [23  2 21 52]]
Shape: (4, 4)
Minimum: 2
Maximum: 99
Mean: 56.75


In [10]:
#Block B
#t1
import numpy as np
a = np.arange(20)
print("First 5 items:", a[:5])
print("Last 3 items:", a[-3:])
print("Even positions:", a[::2])
print("Reversed array:", a[::-1])

#t2
import numpy as np
arr = np.random.randint(0,100,(5,5))
print(arr)
print("First row:")
print(arr[0])
print("Last column:")
print(arr[:,-1])
print("Center 3×3 matrix:")
print(arr[1:4,1:4])
print("Main diagonal:")
print(np.diag(arr))

#t3
import numpy as np
arr = np.random.randint(0,100,(4,4))
print("Original matrix:")
print(arr)
arr[arr > 50] = -1
print("Updated matrix:")
print(arr)

#t4

import numpy as np
a = np.arange(100)
result = a[(a % 3 == 0) & (a % 5 == 0)]
print(result)

#t5 
import numpy as np
scores = np.array([20,55,80,35,60])
result = np.where(scores < 40, "fail", "pass")
print(result)




First 5 items: [0 1 2 3 4]
Last 3 items: [17 18 19]
Even positions: [ 0  2  4  6  8 10 12 14 16 18]
Reversed array: [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[[40 27  6 72 71]
 [11 33 32 47 22]
 [61 87 36 98 43]
 [85 90 34 64 98]
 [46 77  2  0  4]]
First row:
[40 27  6 72 71]
Last column:
[71 22 43 98  4]
Center 3×3 matrix:
[[33 32 47]
 [87 36 98]
 [90 34 64]]
Main diagonal:
[40 33 36 64  4]
Original matrix:
[[89 13 26  8]
 [78 14 89 41]
 [76 50 62 95]
 [51 95  3 93]]
Updated matrix:
[[-1 13 26  8]
 [-1 14 -1 41]
 [-1 50 -1 -1]
 [-1 -1  3 -1]]
[ 0 15 30 45 60 75 90]
['fail' 'pass' 'pass' 'fail' 'pass']


In [14]:
#Block C
#t1
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = np.array([1,2,3])
result = arr + b

print(result)

#t2
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
b = np.array([[1],
              [2],
              [3],
              [4]])

result = arr + b
print(result)

#t3
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
result = a[:,None] * b
print(result)

#t4
import numpy as np

arr = np.random.randint(1,100,(5,4))
print("Original matrix:")
print(arr)
mean = arr.mean(axis=0)
std = arr.std(axis=0)
result = (arr - mean) / std
print("Standardised matrix:")
print(result)



[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Original matrix:
[[23 15 43 29]
 [36 13 32 71]
 [59 86 28 66]
 [42 45 62 57]
 [ 6 28 28 44]]
Standardised matrix:
[[-0.57112617 -0.83419645  0.34044145 -1.59835996]
 [ 0.15677973 -0.90867828 -0.51066218  1.15291538]
 [ 1.44461325  1.80990838 -0.82015441  0.8253826 ]
 [ 0.4927363   0.28303094  1.81052955  0.2358236 ]
 [-1.52300312 -0.35006458 -0.82015441 -0.61576162]]


In [19]:
#block D
#t1
import numpy as np
x = np.linspace(0, 2*np.pi, 10)
print("Values:")
print(x)
print("Sin:")
print(np.sin(x))
print("Cos:")
print(np.cos(x))
print("Tan:")
print(np.tan(x))

#t2
import numpy as np
x = np.arange(1,13).reshape(3,4)
print(x)
pos = np.unravel_index(x.argmax(), x.shape)
print("Position of maximum value:", pos)

#t3
import numpy as np
a = np.array([5,10,15,20,25])
result = (a - a.mean()) / a.std()
print("Standardised array:")
print(result)
print("Mean:", result.mean())
print("Std:", result.std())

#t4

import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
result = np.dot(a,b)
print(result)

#t5
import numpy as np
a = np.array([-10,-3,0,4,7,12,100])
result = np.clip(a,0,10)
print(result)

Values:
[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]
Sin:
[ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]
Cos:
[ 1.          0.76604444  0.17364818 -0.5        -0.93969262 -0.93969262
 -0.5         0.17364818  0.76604444  1.        ]
Tan:
[ 0.00000000e+00  8.39099631e-01  5.67128182e+00 -1.73205081e+00
 -3.63970234e-01  3.63970234e-01  1.73205081e+00 -5.67128182e+00
 -8.39099631e-01 -2.44929360e-16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Position of maximum value: (np.int64(2), np.int64(3))
Standardised array:
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Mean: 0.0
Std: 0.9999999999999999
130
[ 0  0  0  4  7 10 10]


In [22]:
#block E
#t1
import numpy as np

a = np.arange(24)

print("Original:")
print(a)

print("Shape (2,12)")
print(a.reshape(2,12))

print("Shape (3,8)")
print(a.reshape(3,8))

print("Shape (4,6)")
print(a.reshape(4,6))

print("Shape (2,3,4)")
print(a.reshape(2,3,4))

#t2
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

# Row stack
row = np.vstack((a,b))
print("2 row matrix:")
print(row)

# Column stack
col = np.column_stack((a,b))

print("2 column matrix:")
print(col)

#t3
import numpy as np

a = np.arange(20)
parts = np.split(a,4)
print(parts)
result = np.concatenate((parts[0], parts[2]))
print("After joining:")
print(result)

Original:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Shape (2,12)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
Shape (3,8)
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
Shape (4,6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Shape (2,3,4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
2 row matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2 column matrix:
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]
After joining:
[ 0  1  2  3  4 10 11 12 13 14]


In [1]:
#block F
#t1
import numpy as np

# Create fake image batch
imgs = np.random.randint( 0, 256, size=(8,32,32,3),dtype=np.uint8)

# 1. Shape and dtype
print("Shape:", imgs.shape)
print("Data type:", imgs.dtype)

# 2. Mean brightness of each image
brightness = imgs.mean(axis=(1,2,3))

print("Brightness of each image:")
print(brightness)

# 3. Mean of RGB channels
channel_mean = imgs.mean(axis=(0,1,2))

print("Channel mean:")
print(channel_mean)

# 4. Convert RGB to grayscale
gray = imgs.mean(axis=3)

print("Grayscale shape:")
print(gray.shape)

# 5. Standardisation
mean = imgs.mean(axis=(0,1,2))
std = imgs.std(axis=(0,1,2))
standard = (imgs - mean) / std

print("Mean after standardisation:")
print(standard.mean(axis=(0,1,2)))
print("Std after standardisation:")
print(standard.std(axis=(0,1,2)))

# 6. Find brightest image
brightest = brightness.argmax()
print("Brightest image index:")
print(brightest)

Shape: (8, 32, 32, 3)
Data type: uint8
Brightness of each image:
[128.55110677 126.58723958 127.15071615 126.77148438 126.79166667
 129.38151042 127.84667969 126.15071615]
Channel mean:
[126.19665527 128.42907715 127.5859375 ]
Grayscale shape:
(8, 32, 32)
Mean after standardisation:
[ 1.12377555e-16  7.44033741e-18 -3.28513258e-17]
Std after standardisation:
[1. 1. 1.]
Brightest image index:
5
